SOLUTION

function declareWinner(fighter1, fighter2, firstAttacker) {
  var winner = false;
  var puncher, victim, winnerFighter;  
  if(firstAttacker === fighter1.name){
    puncher = fighter1;
    victim = fighter2;
  } else {
    puncher = fighter2;
    victim = fighter1;
  }
  while( !winner && puncher ){
    victim.health -= puncher.damagePerAttack;
    if(victim.health >0){
      var aux = puncher;
      puncher = victim;      
      victim = aux;      
    } else {
      winner = true;
      winnerFighter = puncher;
    }
  }
  return winnerFighter.name;
}



TESTS

Time: 427ms Passed: 206 Failed: 0
Test Results:
 Example Test Cases
Test Passed: Value == 'Lew'
Test Passed: Value == 'Harry'
Test Passed: Value == 'Harald'
Test Passed: Value == 'Harald'
Test Passed: Value == 'Harald'
Test Passed: Value == 'Harald'
Completed in 6ms
 200 Random test cases
Test Passed: Value == 'Bostin'
Test Passed: Value == 'Loyd'
Test Passed: Value == 'Michael'
Test Passed: Value == 'Max'
Test Passed: Value == 'Lui'
Test Passed: Value == 'Lui'
Test Passed: Value == 'Marco'
Test Passed: Value == 'Bostin'
Test Passed: Value == 'Michael'
Test Passed: Value == 'Mario'
Test Passed: Value == 'Bostin'
Test Passed: Value == 'Mark'
Test Passed: Value == 'Mark'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Mark'
Test Passed: Value == 'Michael'
Test Passed: Value == 'Max'
Test Passed: Value == 'Lui'
Test Passed: Value == 'Willy'
Test Passed: Value == 'Mario'
Test Passed: Value == 'Mario'
Test Passed: Value == 'Loyd'
Test Passed: Value == 'Willy'
Test Passed: Value == 'Mark'
Test Passed: Value == 'Mark'
Test Passed: Value == 'Lew'
Test Passed: Value == 'Lui'
Test Passed: Value == 'Max'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Michael'
Test Passed: Value == 'Mario'
Test Passed: Value == 'Bostin'
Test Passed: Value == 'David'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Loyd'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Michael'
Test Passed: Value == 'Loyd'
Test Passed: Value == 'Willy'
Test Passed: Value == 'Mark'
Test Passed: Value == 'Michael'
Test Passed: Value == 'Willy'
Test Passed: Value == 'David'
Test Passed: Value == 'Lui'
Test Passed: Value == 'David'
Test Passed: Value == 'Marco'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Rocky'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Rocky'
Test Passed: Value == 'Max'
Test Passed: Value == 'Bostin'
Test Passed: Value == 'Willy'
Test Passed: Value == 'Lui'
Test Passed: Value == 'Rocky'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Loyd'
Test Passed: Value == 'Loyd'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Max'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Marco'
Test Passed: Value == 'Rocky'
Test Passed: Value == 'Rocky'
Test Passed: Value == 'Rocky'
Test Passed: Value == 'Lew'
Test Passed: Value == 'Lui'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Max'
Test Passed: Value == 'Max'
Test Passed: Value == 'Mark'
Test Passed: Value == 'Loyd'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Willy'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Willy'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Willy'
Test Passed: Value == 'David'
Test Passed: Value == 'Rocky'
Test Passed: Value == 'Max'
Test Passed: Value == 'Mark'
Test Passed: Value == 'Lui'
Test Passed: Value == 'Michael'
Test Passed: Value == 'Lew'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Marco'
Test Passed: Value == 'Bostin'
Test Passed: Value == 'Rocky'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Marco'
Test Passed: Value == 'Michael'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Mario'
Test Passed: Value == 'David'
Test Passed: Value == 'Mark'
Test Passed: Value == 'Michael'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'David'
Test Passed: Value == 'Lew'
Test Passed: Value == 'Mark'
Test Passed: Value == 'Willy'
Test Passed: Value == 'Max'
Test Passed: Value == 'Lew'
Test Passed: Value == 'David'
Test Passed: Value == 'Lew'
Test Passed: Value == 'Max'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Rocky'
Test Passed: Value == 'Rocky'
Test Passed: Value == 'Marco'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Bostin'
Test Passed: Value == 'Lui'
Test Passed: Value == 'Willy'
Test Passed: Value == 'Willy'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Bostin'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Lui'
Test Passed: Value == 'Bostin'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Mario'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Bostin'
Test Passed: Value == 'Mark'
Test Passed: Value == 'Max'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Lui'
Test Passed: Value == 'Marco'
Test Passed: Value == 'Rocky'
Test Passed: Value == 'Max'
Test Passed: Value == 'Willy'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'David'
Test Passed: Value == 'Lew'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Bostin'
Test Passed: Value == 'Mark'
Test Passed: Value == 'Mario'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Marco'
Test Passed: Value == 'David'
Test Passed: Value == 'Mario'
Test Passed: Value == 'Willy'
Test Passed: Value == 'Rocky'
Test Passed: Value == 'Marco'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Lui'
Test Passed: Value == 'Lui'
Test Passed: Value == 'Marco'
Test Passed: Value == 'Mario'
Test Passed: Value == 'David'
Test Passed: Value == 'Lew'
Test Passed: Value == 'Mario'
Test Passed: Value == 'Willy'
Test Passed: Value == 'Willy'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'David'
Test Passed: Value == 'Michael'
Test Passed: Value == 'Marco'
Test Passed: Value == 'Mario'
Test Passed: Value == 'Mario'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Lui'
Test Passed: Value == 'Mark'
Test Passed: Value == 'Mario'
Test Passed: Value == 'Rocky'
Test Passed: Value == 'Mario'
Test Passed: Value == 'Marco'
Test Passed: Value == 'Marco'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Johnny'
Test Passed: Value == 'Rocky'
Test Passed: Value == 'Mark'
Test Passed: Value == 'Michael'
Test Passed: Value == 'Marco'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Patrick'
Test Passed: Value == 'Cuban'
Test Passed: Value == 'Bostin'
Test Passed: Value == 'Willy'
Test Passed: Value == 'Michael'
Completed in 32ms
You have passed all of the tests! :)